pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-21'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        REGISTRY = "shejulv088" // Your Docker Hub username
        APP_NAME = "problemservice" // Change per service
    }

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/VaibhavShejul09/pipeline.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('problemservice') {      // <-- directory relative to workspace
                    sh 'ls -ltr'             // list files
                    sh 'mvn clean package -DskipTests' // build Maven project
                }

            }
        }

        stage('Prepare Docker Tag') {
            steps {
                script {
                    def version = sh(
                        script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout",
                        returnStdout: true
                    ).trim()

                    def shortSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    env.IMAGE_TAG = "${version}-${BUILD_NUMBER}-${shortSha}"
                    env.IMAGE_NAME = "${REGISTRY}/${APP_NAME}:${IMAGE_TAG}"

                    echo "Docker Image: ${IMAGE_NAME}"
                }
            }
        }

        stage('Docker Build') {
            steps {
                
                dir('problemservice') {      // <-- directory relative to workspace
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        stage('Security Scan') {
            steps {
                sh "trivy image ${IMAGE_NAME} || true"
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        sh "docker push ${IMAGE_NAME}"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "CI successful: ${IMAGE_NAME}"
        }
        failure {
            echo "CI failed!"
        }
        cleanup {
            sh 'docker system prune -f || true'
        }
    }
}
