pipeline {
    agent {
        docker {
            image 'maven:3.9.6-eclipse-temurin-21'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/VaibhavShejul09/pipeline.git'
            }
        }

        stage('Build and Test') {
            steps {
                dir('problemservice') {      // <-- directory relative to workspace
                    sh 'ls -ltr'             // list files
                    sh 'mvn clean package -DskipTests' // build Maven project
                }
            }
        }
    }
}
