server.port=8086

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR


# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
#http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Health check for probes 

# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info

# Show detailed health (useful for DB/Redis checks)
management.endpoint.health.show-details=always

# Make actuator use the same port as the server
management.server.port=8086

